### ISSUE TITLE
Skip verification app after update?

### ISSUE THREAD

**Issue by kallookoo** [buo/homebrew-cask-upgrade#123]
Hi,
Beacuse some app using latest version always if update and open this app show the verificating app.
I use one scheduled task (custom bash script) for update brew (packages, casks) and it is a nuisance.

Is possible what skip o run in background after the update the app?

**Comment by ondrejfuhrer** [comment]
Hey @kallookoo that is, unfortunately, not possible. There has been a big discussion about that in Homebrew team and they decided to remove the GPG verification (which causes the pup-up to show) due to user misinterpretation.

You can check the discussion [here](https://github.com/Homebrew/brew/pull/4120#issuecomment-406879969).

**Comment by kallookoo** [comment]
Thanks, @ondrejfuhrer for this info.
