### ISSUE TITLE
Similar tool for brew packages

### ISSUE THREAD

**Issue by Wdavery** [buo/homebrew-cask-upgrade#128]
Is there a sister tool, like `homebrew-upgrade` that works for non-casks? I love the interface this adds to cask upgrading, and it would be amazing to have that brought to brew packages as well. Likely beyond the scope of this project, it is homebrew-**cask**-upgrade after all.

**Comment by ondrejfuhrer** [comment]
My guess would be that there is none. This tap was created before there was an easy way to upgrade apps. Since then there were new commands introduced to list outdated casks and upgrade them. 

For the non-cask formulas that has been supported for much longer therefore there was no need to create such tool. Of course it is nice to have such nice design, but that’s all it actually brings to the table.
