### ISSUE TITLE
What does a `PASS` result mean?

### ISSUE THREAD

**Issue by marnovo** [buo/homebrew-cask-upgrade#142]
I have a few questions regarding the `PASS` results:

1. What do they mean?
2. Why aren't these casks updated even when outdated?
3. Is this related to auto-update apps?

**Comment by ondrejfuhrer** [comment]
Hello @marnovo ,

You're right, `[   PASS   ]` means that the casks won't be updated because they have auto-updates. 

In order to update those as well, use `-a` or `--all` and they will be updated as well (if you want to manually control the version through `brew`).

Does that answer all your questions? 🙂

**Comment by marnovo** [comment]
It does, thanks! Proposed a small change in the readme to clarify it: https://github.com/buo/homebrew-cask-upgrade/pull/143
