### ISSUE TITLE
no upgrade for mas-cli apps 

### ISSUE THREAD

**Issue by CLUB777ONE** [buo/homebrew-cask-upgrade#152]
should homebrew-cask-upgrade also upgrade apps from the MacAppStore that were installed with mas-cli for homebrew, or is that not possible?

**Comment by ondrejfuhrer** [comment]
Hello @CLUB777ONE , thank you for your suggestion. Since right now `brew cu` works only with brew commands, there is no easy way how we could do that (it would have to be built completely separated, etc).

But cool idea, if there is anyone volunteering to build that, might be interesting if that could be added.

**Comment by ondrejfuhrer** [comment]
Hey @CLUB777ONE 

I've just merged this experimental feature so feel free to try It out and give feedback. However, be warned that it solely depends on mas-cli, which isn't perfect (reports some apps that actually don't have an update in MAS, etc), so might be a little bit buggy.
