### ISSUE TITLE
What's meaning of A/U?

### ISSUE THREAD

**Issue by isoulgh** [buo/homebrew-cask-upgrade#188]
![image](https://user-images.githubusercontent.com/47737022/122314776-65105c80-cf4b-11eb-9e3a-1a64b781641f.png)
Some applications are marked a 'Y',others aren't.
What's the meaning of A/U?
Expect for your answer.😃

**Comment by ondrejfuhrer** [comment]
Hello @isoulgh ,

`A/U` means auto-update, those applications have a flag in the cask that they support auto-update functionality, therefore there is a possibility that they updated themselves. That's why in order to update those you need to pass `-a` / `--all` option to update them through `brew cu`.

Hope that makes sense 🙂

**Comment by isoulgh** [comment]
Get it.
Thank you.Thank you.
