### ISSUE TITLE
homebrew/bundle not included , how to install ?

### ISSUE THREAD

**Issue by avichou** [buo/homebrew-cask-upgrade#220]
i tried to see if all the repos were included ,and i get 3 out of the 4 

homebrew/bundle isn't installed

what command should i give to install it ?

**Comment by ondrejfuhrer** [comment]
Hey @avichou ,

Can you please add a little bit more context on what are you trying to do and what's not as expected, ideally with commands that you're running? Thanks.

**Comment by avichou** [comment]
> Hey @avichou ,
> 
> Can you please add a little bit more context on what are you trying to do and what's not as expected, ideally with commands that you're running? Thanks.

sure ,i could add in the post too if necessary 

basically , the installation recommends that you follow these steps to ensure that the program is fully installed : 

In order to simply verify that brew cu is correctly installed, you can simply run brew tap command and see if the repo is included:

> brew tap
buo/cask-upgrade
homebrew/bundle
homebrew/cask
homebrew/core


HOWEVER, after running "brew tap" , i only got 3 of these repos installed, while homebrew/bundle was missing 

it seems to be the reason why nothing happens when i run "brew upgrade" 

hence why i ask, what did i do wrong,and what command should i run in order to have a full install with homebrew/bundle included ?

**Comment by ondrejfuhrer** [comment]
The `homebrew/bundle` isn't strictly necessary for this tap to work, so I wouldn't be worried about that. If you still want to have it, you can simply add it by running `brew tap homebrew/bundle` command.

> it seems to be the reason why nothing happens when i run "brew upgrade"

This is not how you use this extension - in order to use it run `brew cu` and if you have the `buo/cask-upgrade` installed (it is in the list after you ran `brew tap`), should work as expected.

Hope this help.
