### ISSUE TITLE
Merge this tool into homebrew-cask

### ISSUE THREAD

**Issue by ssreekanth** [buo/homebrew-cask-upgrade#23]
I believe this tool should be part of `homebrew-cask`. Any thoughts?

**Comment by buo** [comment]
`brew cask upgrade` has been discussed so many times over and over again on the Homebrew Cask issues since 2013, and many people made their own scripts such as caskroom/homebrew-cask#23658 or [these](http://stackoverflow.com/questions/31968664/upgrade-all-the-casks-installed-via-homebrew-cask). Those are all bash scripts and this tool is written in Ruby, but this is not that stable and fragile too as mentioned [here](https://github.com/caskroom/homebrew-cask/issues/16033#issuecomment-166510222).

Of course, it would be very nice if this tool were merged into the Homebrew Cask, but I think we need to make this stable and add more features like supporting `--appdir` option.

**Comment by jcrben** [comment]
We should at least add the ability to upgrade one by one before merging it into the main project...

**Comment by jcrben** [comment]
If someone can explain the problem with `:latest` succinctly, I'm interested in hearing it...

**Comment by RandomDSdevel** [comment]
@buo:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`brew cask` proper has actually had an `upgrade` sub-command since Homebrew/brew#3396 was merged into upstream's `master` branch with [commit `f50ae44`](https://github.com/Homebrew/brew/commit/f50ae449800c85b53910bf294b9271c45c25da01), so I believe this issue can now be closed.  What that means for the continued development and maintenance of _this_ project remains up to you locals to decide.

**Comment by ondrejfuhrer** [comment]
Closing this, will probably be never merged, already discussed with Homebrew maintainers (https://github.com/buo/homebrew-cask-upgrade/issues/95#issuecomment-396875094)
