### ISSUE TITLE
brew cu doesn't show latest version of app

### ISSUE THREAD

**Issue by ghost** [buo/homebrew-cask-upgrade#52]
<img width="1296" alt="screen shot 2017-03-26 at 12 49 15 pm" src="https://cloud.githubusercontent.com/assets/26471688/24330278/a49037a2-1223-11e7-95f1-90dc6e3442cc.png">

Flow:
- brew update
- (iTerm update popup - clicked no)
- brew cu (attached output)
- go to iTerm + manually update
- brew cu (same as before)

**Comment by ondrejfuhrer** [comment]
There is always some small delay because all the versions need to be "manually" updated by Homebrew Cask contributors. This has nothing to do with `homebrew-cask-upgrade`.

**Comment by selrond** [comment]
@ondrejfuhrer I think the issue is that homebrew-cask-upgrade doesn't recognize manual (in-app) updates. 

So let's say `brew cu` says, iTerm2 Current version is 3.0.14 and Latest is 3.0.15; when you update iTerm2 directly in the app and run `brew cu`, it'll show the same info, as if the app wasn't updated at all.

Anything we can do about it?

**Comment by ondrejfuhrer** [comment]
@selrond Yes, that is true, but not sure if this issue was about that. @ghost was complaining, that `iTerm` prompted for an update (so there is a new version), but `brew cu` says that the version is the latest. That's why the user has to wait until the contributors updates the cask.

Unfortunately, there is not much we can do about the manual updates. The only way, that would be possible, is to check the `appcast` (if set) if it changed. But, since `brew cu` uses `brew cask install` to actually install the app, therefore it has to be updated by `brew cask` contributors for the new version.

So the only thing, we can do, is inform the user "Yes, there is a new version, but you have to wait for the update". Not sure if work the effort, though.
