### ISSUE TITLE
Skipping casks when upgrading all

### ISSUE THREAD

**Issue by ckesc** [buo/homebrew-cask-upgrade#72]
In cask there is option `brew pin` wich prevents `brew upgrade` from updating some cask.
(more info here https://github.com/Homebrew/legacy-homebrew/issues/35714)

I manually pinned cask via `brew pin caskroom/cask/jing` but `brew cu` still trying to update it!

Maybe skip pinned casks?

**Comment by reagle** [comment]
Yes, this would be handy!

**Comment by disrupted** [comment]
with the release of Java 9 I would love a feature like this to keep my installed version.

**Comment by reagle** [comment]
I want it for CarbonCopyCloner. I'm happy with version 4, but version 5 auto-upgrades and requires a new purchase.

**Comment by ondrejfuhrer** [comment]
I'm not sure if that is possible. Does the pinning of the cask actually do the pin? Since I tried it to test it out, but even after running `brew pin caskroom/cask/something` the cask did not appear in `brew list --pinned`. And I didn't find any functionality that allows me to list / get a list of pinned casks. 

Did you manage to do it somehow? There are discussions in Homebrew (in the upgrade thread, etc) about that, but so far no solution.

**Comment by reagle** [comment]
I never got any pinning to work.

**Comment by kdb424** [comment]
This is now an issue for open source synergy users as well as the version that it upgrades to is paid only.

**Comment by ondrejfuhrer** [comment]
@kdb424 Hello, the only solution I see here ATM is to ask guys in the Homebrew Cask repository to split the casks into two versions, one free and one paid. Not sure if they will do it, but if it is really a problem for you, it's worth asking.
