### ISSUE TITLE
Always updating "latest" apps.

### ISSUE THREAD

**Issue by safaiyeh** [buo/homebrew-cask-upgrade#74]
![screen shot 2017-08-23 at 9 05 31 am](https://user-images.githubusercontent.com/8675043/29626276-0e9f7c5e-87e3-11e7-9df0-ae086d0efad5.png)
The casks that use a "latest" channel are always scheduled for an update. Would it be better to only update when there is a change in the latest channel?

**Comment by ondrejfuhrer** [comment]
Unfortunately, we cannot know, if there is any change since the software manufacturer does not tell us. The upgrade depends on the manual update on the cask from the homebrew cask contributors. 

That means that the only information we have is -> it is the latest. There is no concept of checking differences for the "latest" in casks themselves.
