### ISSUE TITLE
Apptivate update bug

### ISSUE THREAD

**Issue by Kamik423** [buo/homebrew-cask-upgrade#86]
```
$ brew cu -facy
<...>
==> Found outdated apps
     Cask       Current  Latest  A/U    Result
1/1  apptivate  latest   latest       [ FORCED ]
==> Upgrading apptivate to latest
==> Satisfying dependencies
==> Downloading http://www.apptivateapp.com/resources/Apptivate.app.zip
######################################################################## 100.0%
==> No checksum defined for Cask apptivate, skipping verification
==> Installing Cask apptivate
Warning: It seems there is already an App at '/Applications/Apptivate.app'; overwriting.
==> Removing App '/Applications/Apptivate.app'.
==> Moving App 'Apptivate.app' to '/Applications/Apptivate.app'.
🍺  apptivate was successfully installed!
==> Removing cached downloads
/Users/<USER>/Library/Caches/Homebrew/Cask/apptivate--latest.zip
==> This operation has freed approximately 745.2KB of disk space.
```
every single time it updates Apptivate. Is this a bug due to homebred-cask-upgrade or due to Apptivate? I already wrote them an email about this. If so is there any way I can temporarily disable autoupdating Apptivate? There does not seem to be any active development on it anymore.

**Comment by ondrejfuhrer** [comment]
The reason is, that you use `-facy` which always (the `f` option) force reinstalls the `latest` apps. Since there is no version of the app (Apptivate does not provide versioning in the download link) there is no way to determine that the version changed. 

So it is partially their fault (they don't provide version) and yours (you use force reinstall option every time). 

There is nothing we can do here.
