### ISSUE TITLE
parallel upgrade?

### ISSUE THREAD

**Issue by ilcn** [buo/homebrew-cask-upgrade#92]
Is it possible to have parallel upgrade?

**Comment by ondrejfuhrer** [comment]
Hey @ilcn 

Thank you for the suggestion, I just tested it and even though it is possible, there are some display issues (especially with progress bar) and I could imagine that it might have as well problems when upgrading casks that depends on each other. 

Would be nice to see here how many people would appreciate this feature with those limitations (there is no much we can do here about the display issues, since that is output of `brew install` command)?

**Comment by ondrejfuhrer** [comment]
Hello guys, as mentioned earlier I don't thing there will be good enough solution to do that. If anyone is able to come up with PR that would solve those issues, feel free to do so, but I think it is too complicated and not worth right now.
